version: "3"

services:
  postgres:
    container_name: "clock-in-app"
    image: "bitnami/postgresql"
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local123
      - POSTGRES_DB=clock-in-app
  rabbit-mq:
    container_name: "clock-in-rabbit-mq"
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672